# permissions for end users to edit visitorsapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: visitorsapp-editor-role
rules:
- apiGroups:
  - visitors.sourcedelica.com
  resources:
  - visitorsapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - visitors.sourcedelica.com
  resources:
  - visitorsapps/status
  verbs:
  - get
